### ISSUE TITLE
Inline popup w/ fuzzy sort, Typescript, SCSS, Webpack, MutationObserver & more

### ISSUE THREAD

**Issue by jkdufair** [dsmiller95/microsoft-teams-emojifier#20]
Hi there -

You can see over at my fork at https://github.com/jkdufair/microsoft-teams-emojifier that I've made quite a few changes & feature additions.  😂 . It also depends on my fork at https://github.com/jkdufair/custom-emoji-server which is api-compatible except for some renaming, I believe. That fork was designed to be able to serve requests at as high a rate as possible (persistent backing store, redis layer, local memory cache)

I'm currently working on electron install on mac (asar appears to be acting strangely - https://github.com/electron/asar/issues/224). And I'm planning on adding slack-like reactions (as replies, probably). And some sort of periodic refresh of emojis.

Not sure if you want to a) have an eventual PR for this stuff? b) have me maintain a fork? c) have me just maintain a separate repo? d) something else?

I will eventually need to deploy to the chrome store for my co-workers to use this, so with that as a constraint, I'm generally fine with any path forward.

**Comment by jkdufair** [comment]
I know you also mentioned in another issue that this is not actively maintained any longer, so I suppose e) make me the maintainer is also an option 🤷

**Comment by dsmiller95** [comment]
Hi!

First off this is awesome, I couldn't be happier that these improvements are being implemented, and it looks like it'll help things run much much smoother 😄 .
I think what I'd like to do for sure is:
1) Add you as a collaborator on this repository and the emoji server repo
2) PR the changes into each respective repo when they're ready

After that it gets fuzzy. From your description what you've built is objectively better than what was there, so I'd like there to be an upgrade path for anyone currently using it. I wish I'd used "emoji" in the api from the start 😅

Maybe the best answer would be for me to update the old api to use the new naming conventions, and preserve that in its own branch. This way anyone maintaining a server wouldn't have to set up the new server in a different environment, and could still benefit from your frontend improvements pushed to the same chrome extension. Does that sound like it'd work with the frontend you're working on?

**Comment by jkdufair** [comment]
Glad you're happy with it all! That approach sounds great. It might be possible to build an interface layer into the emoji server somehow so another persistence layer could be used and/or the redis layer could be optional too. Stuff could possibly be made optional/configurable via a build process as well.

I'll keep you posted with progress. Reactions are going to be tricky.

**Comment by jkdufair** [comment]
Also, if you want to try any of this out, I can PM you the url to our current emoji server. I'd like to build in some auth too but right now it's wide open 😂

**Comment by dsmiller95** [comment]
noice, yeah that could be good in the future! some people might not like being stuck to azure, although it doesn't bother me much.

I'm very interested in how you approach Reactions, The only solution to that I was able to conceptualize was to send messages inside the teams channel with encoded information, and then wire up the extension to consume those messages. which would be awkward as hell. Either that or an external server stores reaction info associated with some sort of message ID 😭

that url would be really handy when it comes time to do sanity checks on the PRs!

**Comment by jkdufair** [comment]
My current thought was similar to your first idea. Something like this:

![image](https://user-images.githubusercontent.com/623494/141194241-290db0b7-1285-4d53-b737-a3cdf4fb9805.png)

Where each line would represent reactions to the first message then each reply. I'd have the extension hide that reply. And it'd have to update that reply as new regular replies come in. Which can be done via an API call - I tested that with cURL.

I'm hoping to have that message be as readable as possible to people not using the extension. Though maybe just making the text display none or transparent or something might be good too.

**Comment by jkdufair** [comment]
It looks like it preserves `<span style="display: none">Foo</span>` on submit, so that may be the best way to go. Even displays none on mobile

**Comment by jkdufair** [comment]
I'm also going to maybe try a side track and attempt some sort of programmatic pasting of an image when completing an emoji command. Then it would be at least viewable by people without the extension and/or on mobile.

**Comment by jkdufair** [comment]
> I'm also going to maybe try a side track and attempt some sort of programmatic pasting of an image when completing an emoji command. Then it would be at least viewable by people without the extension and/or on mobile.

So it turns out messages are limited to 16k for the entire thing including images & text. Many of our emojis are much larger than that (hello, animated gifs 😂 ). So this is probably not feasible. Though there may be a way to upload each of them once as files and then link to wherever they end up in the CDN. Could be risky - who knows how long they stay in that CDN.

**Comment by jkdufair** [comment]
Oh hey - I really couldn't get buy in for me team on this since it wouldn't work with the native apps. I took a different approach and came up with https://github.com/jkdufair/emojinator-macos and https://github.com/jkdufair/emojinator-windows if those are of any interest. Best of luck with this project though!
